### PR TITLE
Remove uses of old_round

### PR DESCRIPTION
**Pull request by Solomon1732**
Remove uses of `old_round` since it's no longer necessary

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
I will remove the Python 2.7 tester since we will only use Python 3 from now on 👍

**Comment by Solomon1732** [comment]
Any news on merging this?

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
Sorry forgot about this one ;)

**Review by devos50 — APPROVED** [review]

**Comment by Solomon1732** [comment]
Ah, ok :smile:

**Pull request merged**
